### ISSUE TITLE
Value of "building_structure_type"

### ISSUE THREAD

**Issue by aDAVISk** [eukarya-inc/plateauutils#24]
"building_structure_type" の値がこのままだと理解できません。何らかの変換をかませて「木造」とか「鉄筋コンクリート」の様な値にすることは可能でしょうか？

**Comment by smellman** [comment]
@aDAVISk 0.0.3リリースで対応しました。ご確認ください。

**Comment by smellman** [comment]
リリース済みなのでクローズします。
