### ISSUE TITLE
Possible to parse without unzip?

### ISSUE THREAD

**Issue by aDAVISk** [eukarya-inc/plateauutils#38]
`CityGMLParser` の` parse` にて、`shutil.unpack_archive` せずに `with zipfile.ZipFile` 内でパースすることは可能でしょうか？

参考資料 https://hacker.trickstorm.com/?p=275

Colabで実行している時に、Google Driveをマウントするとそちらの方に解凍ファイルが流れ込み容量圧迫してしまいます。

**Comment by smellman** [comment]
0.0.7で対応しました。ご確認できましたらクローズをお願いいたします。

**Comment by aDAVISk** [comment]
確認しました。しかもかなり高速化してます。
